Add more required dependencies (#315)
I didn't have docker and got 
```
Error: Docker is unreachable. Docker needs to be running to build inside a container.
```

I didn't have go and got
```
go command not found
```